### ISSUE TITLE
Kimlik kartına sahip kişilerin seri numara bilgisi alınamıyor

### ISSUE THREAD

**Issue by ecmelkytz** [omu/xokul#143]
**Açıklama**

Yeni kimlik kartına sahip kişilerin seri numara bilgisi alınamıyor.

Örnek çıktı:

```
 :new_identity_card_informations=>
   :first_name=>"M***",
   :last_name=>"U***",
   :gender=>{:code=>2, :description=>"Kadın"},
   :date_of_birth=>"1984-11-16",
   :expire_date=>"2029-11-24",
   :place_of_birth=>"Shumen",
   :registry_number=>270046**,
   :serial_number=>0,
   :admission_reason=>{:code=>2, :description=>"Değiştirme"},
```

**Beklenen davranış**

Seri numara bilgisine erişilebilmeli.

**Muhtemel çözüm**

[Şu satırdaki](https://github.com/omu/xokul/blob/dev/app/serializers/kps/queries/identities_serializer.rb#L220) `serial_number`, `integer` yerine `string` yapılmalı.

**Comment by huseyin** [comment]
Fixed by the PR numbered #144
