### ISSUE TITLE
Multi-tenancy desteklenmeli

### ISSUE THREAD

**Issue by msdundar** [omu/xokul#71]
**Açıklama**

- Xokul uygulaması - nokul uygulamasına tenant bazlı BEARER_TOKEN temin etmeli. Örneğin bir nokul instance'ı `omu` için çalışırken, başka bir nokul instance'ı `metu` için çalışabilir. Bunlar xokul'a farklı bearer token'lar ile authorize olacaklar.
- Herhangi bir nokul instance'ı xokul'a authorize olduğunda, bu instance'ın ait olduğu tenant'ın credential'ları kullanılarak harici servislere istek gönderilmeli. Yani `omu`'ye ait YOKSIS kullanıcı adı ve şifresi bilgisini başka müşteriler için kullanamayacağımız göz önünde bulundurulmalı.

**Kontrol listesi**

- [X] İş kaydı başlığının sadece ilk harfi büyük, yazım kurallarına uygun ve emir kipinde
- [X] [Katkı sağlama dokümanına](https://github.com/omu/xokul/CONTRIBUTING.md) uygun

**Comment by huseyin** [comment]
@msdundar Anladım abi seni. Her consumer için ayrı token istiyorsun. BEARER_TOKEN'ları malum API gateway katmanında üretiyoruz. Kong'da (veya gelecekte Tyk'da) her tenant için token üretebiliriz. İşler başlangıçta manuel ilerleyecek. Yani token'ları elle üretip vereceğiz.

Credentials konusuna ise çalışayım biraz. En kestirme nasıl halledebilirim bir araştırayım.

**Comment by msdundar** [comment]
Anlamışsın ama yanlış anlamışsın :) Her tenant için ayrı token'dan bahsetmiyorum. Sen xokul'dan MERNIS'e, YOKSIS'e nasıl istek atıyorsun? OMU'nun credential'larını (devletin OMÜ'ye verdiği kullanıcı adı ve şifre) kullanarak atıyorsun. Bir başka tenant için bunun bu şekilde olmaması lazım.
