### ISSUE TITLE
Ruby sürümü tutarsız tanımlanmış

### ISSUE THREAD

**Issue by msdundar** [omu/xokul#87]
**Açıklama**

- .ruby-version 2.5.3 sürümüne işaret ederken Gemfile 2.6.0 sürümüne işaret ediyor.

**Beklenen davranış**

- Gemfile'ın sürüm bilgisini .ruby-version dosyasından okuması.
- Sürüm olarak 2.6.1 kullanılması.

**Muhtemel çözüm**

- `.ruby-version` => 2.6.1

- `Gemfile` => `ruby File.read('.ruby-version')`

**Comment by huseyin** [comment]
@msdundar Evet Ruby surumunu unstable dali ile ayni tarihte 2.6.0'a yukseltmisim fakat Gemfile'i degistirmemisim [1]. Cok gecmeden duzeltecegim.

[1] https://github.com/omu/xokul/blob/unstable/Gemfile#L6

**Comment by huseyin** [comment]
https://github.com/omu/xokul/commit/dbbfa32f63d85329723337092241fb2b7ddfc757 ve https://github.com/omu/xokul/commit/a9e32efa7255fa10603d122cd8b119cc7e1d2060 numaralı referanslarda düzeltildi.
